apiVersion: v1
kind: Secret
metadata:
    name: ferrisbot
    namespace: ferrisbot
type: Opaque
stringData:
    discord-token: ENC[AES256_GCM,data:OkGi8QR31V68EE3ZZmPa4pB4lewSeCBrUcianbberTr4evYA1+KAL2aHfXQDBZWKlSbpP3sTYcI+6+tgHyQ1kGVvJDht7w==,iv:X+2IpEuvAfyo4tsiHgfrw9hyREcCxntxQjC0YVXkzNE=,tag:OCADm+0NjOC413RekVNq6A==,type:str]
    honeycomb-headers: ENC[AES256_GCM,data:aOkGQ3OzJn6TpIdyxDCerG3weun1uCMQ247p+d4atqnVEPQIDCTz42c8vM0AooXGPwaFZwRu4acuavxHIU5QXLeSBYq6TaKqzU5vMLUHdH6E,iv:5rtS8Y2IFkIyQj0S6ygF4TMMVWMTOX1Ghq+Fswiygwo=,tag:5xSGKVSMKqdCFHgTqULYeQ==,type:str]
sops:
    age:
        - recipient: age1d36v9zvqg5fraumcpg470etkjtztyz0fw8dgj5v5pmd9mr0t29zq3gzkhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSEc5Z3doOEoyV09LcjVz
            VUk4aVB5Uk1DQit5TUErT0JGbENPQ0N0WlhzCjlSZW5OVis0Z0hOeFFja3N5RDFK
            MEV3WFVLU3ZjM3VPUjhqdE15L3pHa0kKLS0tIFpjczNRZUhod3oxZ05td0ZVRE9Z
            em85eDNVdG9rZGZkcnhvcjhUdTc0NnMKiw51f5B3Q9B+QbZO0ESV62ur7+NE12dL
            zycu3X3zUEl2OXI7dEsRIu3sJUn9gQEPUo5btrL82EKjJCP7f3w2Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:43:01Z"
    mac: ENC[AES256_GCM,data:qfN/+HqnkHCJ5nB6XiDAme9oVLubQP3VpMj5twUkfhirZDPjXoBd04TM9BjtEEVnlSi3ebaKrEGrIlT+UOoHO5TAHa284M/A5L/XUtpd410HMdaH3V89EObKVNdIYEitipB/cRr0meNUsaVqWP+nK8gymSLQZMc+taFLA0u/PTE=,iv:C4iaLFABJm22BVifTj08EoaJVT6JFMxSuvHrj4PLJ/w=,tag:q+19aCWoP/PoiIFgnVcbVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
